"""add_index_daily_daily_basic_industry_member

Revision ID: 10c339861d8e
Revises: 977c95558b60
Create Date: 2026-04-14 10:26:46.487548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c339861d8e'
down_revision: Union[str, Sequence[str], None] = '977c95558b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_basic',
    sa.Column('ts_code', sa.String(length=12), nullable=False, comment='TS代码，如 000001.SZ'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('turnover_rate', sa.Numeric(precision=10, scale=4), nullable=True, comment='换手率（%）'),
    sa.Column('turnover_rate_f', sa.Numeric(precision=10, scale=4), nullable=True, comment='换手率（自由流通股）'),
    sa.Column('volume_ratio', sa.Numeric(precision=10, scale=4), nullable=True, comment='量比'),
    sa.Column('pe', sa.Numeric(precision=12, scale=4), nullable=True, comment='市盈率（总市值/净利润）'),
    sa.Column('pe_ttm', sa.Numeric(precision=12, scale=4), nullable=True, comment='市盈率（TTM）'),
    sa.Column('pb', sa.Numeric(precision=12, scale=4), nullable=True, comment='市净率'),
    sa.Column('ps', sa.Numeric(precision=12, scale=4), nullable=True, comment='市销率'),
    sa.Column('ps_ttm', sa.Numeric(precision=12, scale=4), nullable=True, comment='市销率（TTM）'),
    sa.Column('dv_ratio', sa.Numeric(precision=10, scale=4), nullable=True, comment='股息率（%）'),
    sa.Column('dv_ttm', sa.Numeric(precision=10, scale=4), nullable=True, comment='股息率（TTM）（%）'),
    sa.Column('total_share', sa.Numeric(precision=20, scale=4), nullable=True, comment='总股本（万股）'),
    sa.Column('float_share', sa.Numeric(precision=20, scale=4), nullable=True, comment='流通股本（万股）'),
    sa.Column('free_share', sa.Numeric(precision=20, scale=4), nullable=True, comment='自由流通股本（万股）'),
    sa.Column('total_mv', sa.Numeric(precision=20, scale=4), nullable=True, comment='总市值（万元）'),
    sa.Column('circ_mv', sa.Numeric(precision=20, scale=4), nullable=True, comment='流通市值（万元）'),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date'),
    comment='每日基本面指标表（估值/换手率/市值）'
    )
    op.create_index('ix_daily_basic_trade_date', 'daily_basic', ['trade_date'], unique=False)
    op.create_index('ix_daily_basic_ts_code', 'daily_basic', ['ts_code'], unique=False)
    op.create_table('index_daily',
    sa.Column('ts_code', sa.String(length=12), nullable=False, comment='指数代码，如 000300.SH'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=True, comment='开盘点位'),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=True, comment='最高点位'),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=True, comment='最低点位'),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=True, comment='收盘点位'),
    sa.Column('pre_close', sa.Numeric(precision=12, scale=4), nullable=True, comment='昨收点位'),
    sa.Column('change', sa.Numeric(precision=12, scale=4), nullable=True, comment='涨跌额'),
    sa.Column('pct_chg', sa.Numeric(precision=10, scale=4), nullable=True, comment='涨跌幅（%）'),
    sa.Column('vol', sa.Numeric(precision=20, scale=2), nullable=True, comment='成交量（手）'),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=True, comment='成交额（千元）'),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date'),
    comment='指数日线行情表'
    )
    op.create_index('ix_index_daily_trade_date', 'index_daily', ['trade_date'], unique=False)
    op.create_index('ix_index_daily_ts_code', 'index_daily', ['ts_code'], unique=False)
    op.create_table('industry_member',
    sa.Column('index_code', sa.String(length=20), nullable=False, comment='行业指数代码'),
    sa.Column('ts_code', sa.String(length=12), nullable=False, comment='成分股TS代码'),
    sa.Column('index_name', sa.String(length=50), nullable=True, comment='行业指数名称'),
    sa.Column('con_name', sa.String(length=50), nullable=True, comment='成分股名称'),
    sa.Column('in_date', sa.Date(), nullable=True, comment='纳入日期'),
    sa.Column('out_date', sa.Date(), nullable=True, comment='剔除日期'),
    sa.Column('is_new', sa.String(length=1), nullable=True, comment='是否最新 Y/N'),
    sa.PrimaryKeyConstraint('index_code', 'ts_code'),
    comment='行业成分股映射表'
    )
    op.create_index('ix_industry_member_index_code', 'industry_member', ['index_code'], unique=False)
    op.create_index('ix_industry_member_ts_code', 'industry_member', ['ts_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_industry_member_ts_code', table_name='industry_member')
    op.drop_index('ix_industry_member_index_code', table_name='industry_member')
    op.drop_table('industry_member')
    op.drop_index('ix_index_daily_ts_code', table_name='index_daily')
    op.drop_index('ix_index_daily_trade_date', table_name='index_daily')
    op.drop_table('index_daily')
    op.drop_index('ix_daily_basic_ts_code', table_name='daily_basic')
    op.drop_index('ix_daily_basic_trade_date', table_name='daily_basic')
    op.drop_table('daily_basic')
    # ### end Alembic commands ###
