"""create_initial_tables

Revision ID: 977c95558b60
Revises: 
Create Date: 2026-04-08 15:47:06.540786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '977c95558b60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adj_factor',
    sa.Column('ts_code', sa.String(length=12), nullable=False, comment='TS代码，如 000001.SZ'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('adj_factor', sa.Numeric(precision=20, scale=6), nullable=True, comment='复权因子（后复权基准）'),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date'),
    comment='复权因子表'
    )
    op.create_index('ix_adj_factor_trade_date', 'adj_factor', ['trade_date'], unique=False)
    op.create_index('ix_adj_factor_ts_code', 'adj_factor', ['ts_code'], unique=False)
    op.create_table('stock_basic',
    sa.Column('ts_code', sa.String(length=12), nullable=False, comment='TS代码，如 000001.SZ'),
    sa.Column('symbol', sa.String(length=10), nullable=False, comment='股票代码，如 000001'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='股票名称'),
    sa.Column('area', sa.String(length=30), nullable=True, comment='地域'),
    sa.Column('industry', sa.String(length=50), nullable=True, comment='所属行业'),
    sa.Column('market', sa.String(length=20), nullable=True, comment='市场类型：主板/创业板/科创板/北交所'),
    sa.Column('exchange', sa.String(length=10), nullable=True, comment='交易所：SSE/SZSE/BSE'),
    sa.Column('curr_type', sa.String(length=5), nullable=True, comment='交易货币'),
    sa.Column('list_status', sa.String(length=1), nullable=True, comment='上市状态：L=上市 D=退市 P=暂停'),
    sa.Column('list_date', sa.Date(), nullable=True, comment='上市日期'),
    sa.Column('delist_date', sa.Date(), nullable=True, comment='退市日期'),
    sa.Column('is_hs', sa.String(length=1), nullable=True, comment='沪深港通：N=否 H=沪股通 S=深股通'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='本地最后更新时间'),
    sa.PrimaryKeyConstraint('ts_code')
    )
    op.create_table('stock_daily',
    sa.Column('ts_code', sa.String(length=12), nullable=False, comment='TS代码，如 000001.SZ'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=True, comment='开盘价（元）'),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=True, comment='最高价（元）'),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=True, comment='最低价（元）'),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=True, comment='收盘价（元）'),
    sa.Column('pre_close', sa.Numeric(precision=12, scale=4), nullable=True, comment='昨收价（元）'),
    sa.Column('change', sa.Numeric(precision=12, scale=4), nullable=True, comment='涨跌额（元）'),
    sa.Column('pct_chg', sa.Numeric(precision=10, scale=4), nullable=True, comment='涨跌幅（%），非复权'),
    sa.Column('vol', sa.Numeric(precision=20, scale=2), nullable=True, comment='成交量（手）'),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=True, comment='成交额（千元）'),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date'),
    comment='日线行情表（未复权）'
    )
    op.create_index('ix_stock_daily_trade_date', 'stock_daily', ['trade_date'], unique=False)
    op.create_index('ix_stock_daily_ts_code', 'stock_daily', ['ts_code'], unique=False)
    op.create_table('trade_cal',
    sa.Column('exchange', sa.String(length=10), nullable=False, comment='交易所代码，如 SSE / SZSE'),
    sa.Column('cal_date', sa.Date(), nullable=False, comment='日历日期'),
    sa.Column('is_open', sa.SmallInteger(), nullable=False, comment='是否交易日：1=是 0=否'),
    sa.Column('pretrade_date', sa.Date(), nullable=True, comment='上一个交易日'),
    sa.PrimaryKeyConstraint('exchange', 'cal_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_cal')
    op.drop_index('ix_stock_daily_ts_code', table_name='stock_daily')
    op.drop_index('ix_stock_daily_trade_date', table_name='stock_daily')
    op.drop_table('stock_daily')
    op.drop_table('stock_basic')
    op.drop_index('ix_adj_factor_ts_code', table_name='adj_factor')
    op.drop_index('ix_adj_factor_trade_date', table_name='adj_factor')
    op.drop_table('adj_factor')
    # ### end Alembic commands ###
