"""add_stk_holdernumber_table

Revision ID: a28fe9f9e17d
Revises: 10c339861d8e
Create Date: 2026-04-30 10:59:57.821626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a28fe9f9e17d'
down_revision: Union[str, Sequence[str], None] = '10c339861d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stk_holdernumber',
    sa.Column('ts_code', sa.String(length=12), nullable=False, comment='TS代码，如 000001.SZ'),
    sa.Column('ann_date', sa.Date(), nullable=False, comment='公告日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='截止日期（报告期）'),
    sa.Column('holder_num', sa.Integer(), nullable=True, comment='股东户数'),
    sa.PrimaryKeyConstraint('ts_code', 'ann_date'),
    comment='股东人数表（筹码集中度分析）'
    )
    op.create_index('ix_stk_holdernumber_end_date', 'stk_holdernumber', ['end_date'], unique=False)
    op.create_index('ix_stk_holdernumber_ts_code', 'stk_holdernumber', ['ts_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stk_holdernumber_ts_code', table_name='stk_holdernumber')
    op.drop_index('ix_stk_holdernumber_end_date', table_name='stk_holdernumber')
    op.drop_table('stk_holdernumber')
    # ### end Alembic commands ###
